### ISSUE TITLE
Transfer ownership of rtd and pipy

### ISSUE THREAD

**Issue by hippalectryon-0** [hippalectryon-0/xr-scipy#20]
@fujiisoup I've finally managed to fix most utests, docs and modules (I think ^^). I've put a temporary new readthedocs [here](https://xr-scipy-test.readthedocs.io/en/latest/fft.html), but I think it's better for everyone if we keep the same page for the docs and the pipy.

Could you also transfer the ownership / share the rights of the readthedocs project and the pipy project ?

Thanks !

**Comment by fujiisoup** [comment]
Thank you @hippalectryon-0 for taking over the development / maintenance.
I think I sent an invitation as a maintainer of readthedocs. 
Let me know if you did not get anything.
