### ISSUE TITLE
Cannot call xrscipy functions

### ISSUE THREAD

**Issue by Yefee** [hippalectryon-0/xr-scipy#27]
Just instnalled the xrscipy using the toml file, and it can be imported successfully. But seems I cannot call any xrscipy functions.

<img width="932" alt="CleanShot 2023-05-26 at 12 40 10@2x" src="https://github.com/hippalectryon-0/xr-scipy/assets/6420873/1621346e-eb8c-41fb-89cd-d5b0fdd1e46a">

**Comment by hippalectryon-0** [comment]
You need to import `xrscipy.integrate` and not just `xrscipy`.

I've updated the README accordingly.
