### ISSUE TITLE
Refactor FFT

### ISSUE THREAD

**Issue by fujiisoup** [hippalectryon-0/xr-scipy#3]
Xarray.apply_ufunc now disallow to change the dimension size of input_core_dims.
xrscipy.fft uses this. needs update.

Also, it might be reasonable to merge fft and fftn function.

**Comment by hippalectryon-0** [comment]
Dimension change done in dev0.

In the current state I'm not sure we want to merge fft and fftn, they don't have the same signature in scipy.
