### ISSUE TITLE
move xrscipy.other.signal to xrscipy.signal as it was before

### ISSUE THREAD

**Issue by smartass101** [hippalectryon-0/xr-scipy#36]
I appreciate you took over the maintenance burden @hippalectryon-0, I really do. 
Is there a good reason why you moved the signal wrappers into the "other" subpackage? They do follow the `scipy` naming, so putting them under `other` is rather confusing for users, especially to those who used the older `xrscipy.signal` module and now wonder where it went.

**Comment by hippalectryon-0** [comment]
The functions put in `xrscipy.other` are meant to be functions that don't have an equivalent in scipy.

Concerning `xrscipy.other.signal`, we find a mix of `scipy.signal` functions (`csd, spectrogram, coherence, hilbert`) and functions not found in `xrscipy.signal` (`crossspectrogram, freq2lag, xcorrelation, psd, coherogram`), and given the current balance I previously chose to put everything in `xrscipy.other`.

Do you think it would be better to split the package and put `csd, spectrogram, coherence, hilbert` in `xrscipy.signal` while keeping the others as-is in `xrscipy.other.signal` ?

**Comment by hippalectryon-0** [comment]
Can you check if https://github.com/hippalectryon-0/xr-scipy/releases/tag/2.0.0.pre does what you wanted ?

**Comment by smartass101** [comment]
Thanks, that looks good. I actually had in mind really moving the "extra" functions to separate modules, but I think your approach of just splitting the namespaces is a better compromise in terms of maintainability. Truly splitting stuff into separate non-extra and extra modules + sharing the helpers in between would be possibly more difficult to maintain.
I just feel I should point out in the interest of clarity that in principle just importing anything from `filters`  (i.e. even if just using the non-extra namespace) registers the `.filt accessor
https://github.com/hippalectryon-0/xr-scipy/blob/d1bd88a284a2ddcfe74b04c7ed7ae28cef2e487f/xrscipy/signal/filters.py#L556

**Comment by hippalectryon-0** [comment]
ok !
I'll make an official release in a few days.
