### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by ckutlu** [hippalectryon-0/xr-scipy#47]
Hello @hippalectryon-0, I was wondering if it would be possible to relax the python requirements, preferably matching the [one in xarray](https://github.com/pydata/xarray/blob/879b06b06fe2a08dcc1104761b32a31b64b7d74b/pyproject.toml#L23) which is:
```
requires-python = ">=3.9"
```

**Comment by hippalectryon-0** [comment]
The reason why we require 3.10 is to allow using "|" in python typing hints, which is only available from 3.10 onwards.
If for some reason you are on an environment where you are limited to 3.9 (which shouldn't happen in 2024!), one workaround would be to ~~blame your outdated server administrators~~ fork the repository, remove the type hints from the code, and pip install using your new repository.

**Comment by ckutlu** [comment]
Thanks for the reply.  The reason why we need to support 3.9 is a bit more complicated than updating our environment (and somewhat typical if you ask my opinion): We serve code to people who may still want to use python 3.9 (unfortunately we can't really force them what to use). I understand your point about the type hints. If having union type expressions is the only blocker, I'd recommend using `from __future__ import annotations` which provides the backport of that feature. I'd be happy to make the necessary changes and make a pull request if you agree with that approach. Whatever your response might be, I totally understand where you are coming from and definitely don't want to sound pushy with a feature request here. I greatly appreciate the work you've put into this library :rocket:

**Comment by hippalectryon-0** [comment]
Feel free to go ahead and submit a PR ! I'll happily merge it :)

**Comment by hippalectryon-0** [comment]
Let me know if `2.1.0` works fine for you :)

**Comment by ckutlu** [comment]
Works like a charm :) Many thanks.

Side note: I realized I forgot to add any changelog entry to my PR and now the changelog for 2.1.0 is rather empty. Do we need a PR for that?

**Comment by hippalectryon-0** [comment]
Write it here and I'll edit it to the github release

**Comment by ckutlu** [comment]
How about this:

> Add support for python 3.9 and 3.12.

**Comment by hippalectryon-0** [comment]
done! feel free to close the issue :)
